INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["carte mere Asus TUF GAMING B550-PLUS","Asus TUF GAMING B550-PLUS",180,"Asus","B550","AM4","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,2]


INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["carte mere Gigabyte B550M DS3H","Gigabyte B550M DS3H",220,"Gigabyte","B650","AM4","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,2]


INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["carte mere ASRock B550 Pro4","ASRock B550 Pro4",120,"ASRock","B650","AM4","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,2]



INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["carte mere MSI MAG B650 Tomahawk WIFI","MSI MAG B650 Tomahawk WIFI",350,"MSI","B650","AM5","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,2]


INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["Carte Graphique Gainward GeForce RTX 4070 Ghost","Gainward GeForce RTX 4070 Ghost",649,"Gainward","","","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,6]


INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["Carte Graphique KFA2 GeForce GTX 1630 EX (1-Click OC)","KFA2 GeForce GTX 1630 EX (1-Click OC)",169,"KFA2","","","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,6]



INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["Carte Graphique Sapphire PULSE Radeon RX 6700 XT","Sapphire PULSE Radeon RX 6700 XT",399,"Sapphire","","","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,6]


INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["Carte Graphique Sapphire PULSE Radeon RX 6700 XT","Sapphire PULSE Radeon RX 6700 XT",399,"Sapphire","","","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,6]


INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["Processeur AMD Ryzen 5 5500 (3.6 GHz)","AMD Ryzen 5 5500 (3.6 GHz)",129,"AMD","","AM4","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,1]

INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["Processeur Intel Core i5-10400F (2.9 GHz)","Intel Core i5-10400F (2.9 GHz)",108,"INTEL","","1200","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,1]

INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["Processeur Intel Core i5-13400 (2.5 GHz)","Intel Core i5-13400 (2.5 GHz)",263,"INTEL","","1700","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,1]


INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["Processeur AMD Ryzen 9 7950X3D (4.2 GHz)","AMD Ryzen 9 7950X3D (4.2 GHz)",827,"AMD","","am5","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,1]


INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["Ventirad Fox Spirit Cold Snap XT120 Black","Fox Spirit Cold Snap XT120 Black",59,"Fox","1700","am5","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,5]

INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["Ventirad be quiet! Pure Rock 2 Black","be quiet! Pure Rock 2 Black",42,"be quiet!","1700","am5","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,5]

INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["Ventirad Cooler Master Hyper TX3 EVO","Cooler Master Hyper TX3 EVO",24,"Cooler Master","1700","am5","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,5]


INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["Ventirad AMD Wraith Prism","AMD Wraith Prism",40,"amd","1700","am5","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,5]


INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["Ram DDR4 Corsair Vengeance LPX Noir - 32 Go (2 x 16 Go) 3200 MHz - CAS 16","DDR4 Corsair Vengeance LPX Noir - 32 Go (2 x 16 Go) 3200 MHz - CAS 16",79,"Corsair","1700","am5","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,3]


INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["Ram DDR4 Kingston Fury Beast - 16 Go (2 x 8 Go) 3200 MHz - CAS 16","DDR4 Kingston Fury Beast - 16 Go (2 x 8 Go) 3200 MHz - CAS 16",65,"Kingston","1700","am5","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,3]


INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["Ram DDR4 G.Skill Aegis - 16 Go (2 x 8 Go) 3200 MHz - CAS 16","DDR4 G.Skill Aegis - 16 Go (2 x 8 Go) 3200 MHz - CAS 16",54,"G.Skill","1700","am5","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,3]


INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["Ram DDR4 Textorm - 32 Go 3200 MHz - CAS 16","DDR4 Textorm - 32 Go 3200 MHz - CAS 16",109,"Textorm","1700","am5","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,3]


INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["Boitier Corsair 4000D Airflow - Noir","Corsair 4000D Airflow - Noir",99,"Corsair","1700","am5","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,4]


INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["Boitier NZXT H5 Flow - Blanc","NZXT H5 Flow - Blanc",109,"NZXT","1700","am5","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,4]



INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["Boitier Zalman S5 - Noir","Zalman S5 - Noir",70,"NZXT","1700","am5","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,4]


INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["Boitier Aerocool Cylon Mini - Noir","Aerocool Cylon Mini - Noir",45,"Aerocool","1700","am5","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,4]


INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["Alimentation Corsair HX750 - 750W","Corsair HX750 - 750W",149,"Corsair","1700","am5","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,7]


INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["Alimentation MSI MPG A850G PCIE5 - 850W","MSI MPG A850G PCIE5 - 850W",165,"MSI","1700","am5","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,7]


INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["Alimentation Seasonic FOCUS PX - 650W","Seasonic FOCUS PX - 650W",139,"Seasonic","1700","am5","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,7]


INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["Alimentation Corsair SF600 - 600W (SFX)","Corsair SF600 - 600W (SFX)",134,"Corsair","1700","am5","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,7]



INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["SSD Crucial BX500 500 Go","Crucial BX500 500 Go",39,"Crucial","1700","am5","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,8]


INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["SSD Samsung 980 1 To","Samsung 980 1 To",69,"Samsung","1700","am5","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,8]


INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["SSD Textorm BM5 240 Go","Textorm BM5 240 Go",18,"Textorm","1700","am5","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,8]


INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["SSD Kingston A400 240 Go","Kingston A400 240 Go",25,"Kingston","1700","am5","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,8]


INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["HDD Seagate BarraCuda 1 To","Seagate BarraCuda 1 To",40,"Seagate","1700","am5","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,9]


INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["HDD Toshiba X300 4 To","Toshiba X300 4 To",108,"Toshiba","1700","am5","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,9]


INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["HDD Western Digital WD Blue 1 To","Western Digital WD Blue 1 To",42,"Western Digital","1700","am5","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,9]


INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["HDD Seagate IronWolf Pro 14 To","Seagate IronWolf Pro 14 To",419,"Seagate","1700","am5","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,9]



INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["Carte-Son Carte Son - Son 3D 5.1 - USB 2.0","Carte Son - Son 3D 5.1 - USB 2.0",9,"son 3D","1700","am5","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,11]


INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["Carte-Son EPOS | Sennheiser GSX 1200 PRO","EPOS | Sennheiser GSX 1200 PRO",224,"Sennheiser","1700","am5","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,11]



INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["Carte-Son Startech ICUSBAUDIO2D","Startech ICUSBAUDIO2D",39,"Startech","1700","am5","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,11]


INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["Carte-Son Asus Xonar U5","Asus Xonar U5",82,"Xonar","1700","am5","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,11]



INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["Carte-Reseau StarTech ST1000SPEX2","StarTech ST1000SPEX2",24,"StarTech","1700","am5","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,12]


INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["Carte-Reseau Asus XG-C100F","Asus XG-C100F",147,"Asus","1700","am5","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,12]



INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["Carte-Reseau Asustor AS-T10G2","Asustor AS-T10G2",129,"Asustor","1700","am5","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,12]



INSERT INTO "components"(
    "name",
     "description",
      "price",
       "marque",
        "chipset",
         "socket",
          "format_cm",
           "slot_nvme",
            "slot_sata",
             "ram_number",
              "ram_frequence",
               "ram_capacite",
                "format_alim",
                 "format_boitier",
                  "ssd_nvme",
                   "ssd_sata",
                    "hdd_sata",
                     "pci",
                      "typesId") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING "id" -- PARAMETERS: ["Carte-Reseau TP-Link TX401","TP-Link TX401",95,"TP-Link","1700","am5","Atx",0,0,0,"2133 Mhz","8Go","Atx","Atx",0,0,0,0,12]